-- Private vault database (binding VAULT_DB). Holds ONLY ciphertext, public key-derivation parameters,
-- nonces/tags and wrapped keys. No plaintext tickers, balances or hashes of private content.
-- Hand-written and append-only (not generated by drizzle-kit): never edit this file, add a new one.
CREATE TABLE `vaults` (
	`vault_id` text PRIMARY KEY NOT NULL,
	`owner` text NOT NULL,
	`format_version` integer NOT NULL,
	`key_version` integer NOT NULL,
	`wrapper_version` integer NOT NULL,
	`password_wrapper` text NOT NULL,
	`recovery_wrapper` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_vaults_owner` ON `vaults` (`owner`);
--> statement-breakpoint
CREATE TABLE `vault_portfolios` (
	`vault_id` text PRIMARY KEY NOT NULL,
	`envelope` text NOT NULL,
	`revision` integer NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`vault_id`) REFERENCES `vaults`(`vault_id`) ON UPDATE no action ON DELETE cascade
);
